In [1]:
import polars as pl

In [2]:
pl.build_info()

{'compiler': {'rustc': '/root/.rustup/toolchains/nightly-2024-06-23-x86_64-unknown-linux-gnu/bin/rustc',
  'rustc-version': 'rustc 1.81.0-nightly (3cb521a43 2024-06-22)',
  'opt-level': '3',
  'debug': False,
  'jobs': 4},
 'time': 'Sun, 7 Jul 2024 10:12:46 +0000',
 'dependencies': {'addr2line': '0.22.0',
  'adler': '1.0.2',
  'adler32': '1.2.0',
  'ahash': '0.8.11',
  'aho-corasick': '1.1.3',
  'alloc-no-stdlib': '2.0.4',
  'alloc-stdlib': '0.2.2',
  'allocator-api2': '0.2.18',
  'android-tzdata': '0.1.1',
  'android_system_properties': '0.1.5',
  'anes': '0.1.6',
  'anstyle': '1.0.7',
  'anyhow': '1.0.86',
  'apache-avro': '0.16.0',
  'arboard': '3.4.0',
  'argminmax': '0.6.2',
  'array-init-cursor': '0.2.0',
  'arrayref': '0.3.7',
  'arrayvec': '0.7.4',
  'arrow-array': '52.0.0',
  'arrow-buffer': '52.0.0',
  'arrow-data': '52.0.0',
  'arrow-schema': '52.0.0',
  'arrow2': '0.17.4',
  'async-stream': '0.3.5',
  'async-stream-impl': '0.3.5',
  'async-trait': '0.1.80',
  'atoi': '2.0.0',
  'atoi_simd': '0.15.6',
  'atomic-waker': '1.1.2',
  'autocfg': '1.3.0',
  'avro-schema': '0.3.0',
  'aws-config': '1.5.3',
  'aws-credential-types': '1.2.0',
  'aws-runtime': '1.3.0',
  'aws-sdk-s3': '1.31.0',
  'aws-sdk-sso': '1.33.0',
  'aws-sdk-ssooidc': '1.34.0',
  'aws-sdk-sts': '1.33.0',
  'aws-sigv4': '1.2.2',
  'aws-smithy-async': '1.2.1',
  'aws-smithy-checksums': '0.60.8',
  'aws-smithy-eventstream': '0.60.4',
  'aws-smithy-http': '0.60.8',
  'aws-smithy-json': '0.60.7',
  'aws-smithy-query': '0.60.7',
  'aws-smithy-runtime': '1.6.0',
  'aws-smithy-runtime-api': '1.7.0',
  'aws-smithy-types': '1.2.0',
  'aws-smithy-xml': '0.60.8',
  'aws-types': '1.3.2',
  'backtrace': '0.3.73',
  'base16ct': '0.1.1',
  'base64': '0.22.1',
  'base64-simd': '0.8.0',
  'base64ct': '1.6.0',
  'bincode': '1.3.3',
  'bitflags': '2.6.0',
  'blake3': '1.5.1',
  'block-buffer': '0.10.4',
  'block2': '0.5.1',
  'brotli': '6.0.0',
  'brotli-decompressor': '4.0.1',
  'built': '0.7.3',
  'bumpalo': '3.16.0',
  'bytemuck': '1.16.1',
  'bytemuck_derive': '1.7.0',
  'bytes': '1.6.0',
  'bytes-utils': '0.1.4',
  'cargo-lock': '9.0.0',
  'casey': '0.4.0',
  'cast': '0.3.0',
  'cc': '1.0.101',
  'cfg-if': '1.0.0',
  'chrono': '0.4.38',
  'chrono-tz': '0.8.6',
  'chrono-tz-build': '0.2.1',
  'ciborium': '0.2.2',
  'ciborium-io': '0.2.2',
  'ciborium-ll': '0.2.2',
  'clap': '4.5.8',
  'clap_builder': '4.5.8',
  'clap_lex': '0.7.1',
  'clipboard-win': '5.3.1',
  'cmake': '0.1.50',
  'comfy-table': '7.1.1',
  'const-oid': '0.9.6',
  'const-random': '0.1.18',
  'const-random-macro': '0.1.16',
  'constant_time_eq': '0.3.0',
  'core-foundation': '0.9.4',
  'core-foundation-sys': '0.8.6',
  'core2': '0.4.0',
  'cpufeatures': '0.2.12',
  'crc': '2.1.0',
  'crc-catalog': '1.1.1',
  'crc32c': '0.6.8',
  'crc32fast': '1.4.2',
  'criterion': '0.5.1',
  'criterion-plot': '0.5.0',
  'crossbeam-channel': '0.5.13',
  'crossbeam-deque': '0.8.5',
  'crossbeam-epoch': '0.9.18',
  'crossbeam-queue': '0.3.11',
  'crossbeam-utils': '0.8.20',
  'crossterm': '0.27.0',
  'crossterm_winapi': '0.9.1',
  'crunchy': '0.2.2',
  'crypto-bigint': '0.5.5',
  'crypto-common': '0.1.6',
  'dary_heap': '0.3.6',
  'der': '0.6.1',
  'deranged': '0.3.11',
  'digest': '0.10.7',
  'doc-comment': '0.3.3',
  'dyn-clone': '1.0.17',
  'ecdsa': '0.14.8',
  'either': '1.13.0',
  'elliptic-curve': '0.12.3',
  'enum_dispatch': '0.3.13',
  'env_logger': '0.8.4',
  'equivalent': '1.0.1',
  'errno': '0.3.9',
  'error-code': '3.2.0',
  'ethnum': '1.5.0',
  'fallible-streaming-iterator': '0.1.9',
  'fast-float': '0.2.0',
  'fastrand': '2.1.0',
  'ff': '0.12.1',
  'flate2': '1.0.30',
  'float-cmp': '0.9.0',
  'fnv': '1.0.7',
  'foreign_vec': '0.1.0',
  'form_urlencoded': '1.2.1',
  'fs4': '0.8.4',
  'futures': '0.3.30',
  'futures-channel': '0.3.30',
  'futures-core': '0.3.30',
  'futures-executor': '0.3.30',
  'futures-io': '0.3.30',
  'futures-macro': '0.3.30',
  'futures-sink': '0.3.30',
  'futures-task': '0.3.30',
  'futures-util': '0.3.30',
  'generic-array': '0.14.7',
  'gethostname': '0.4.3',
  'getrandom': '0.2.15',
  'gimli': '0.29.0',
  'git2': '0.18.3',
  'glob': '0.3.1',
  'group': '0.12.1',
  'h2': '0.4.5',
  'half': '2.4.1',
  'halfbrown': '0.2.5',
  'hash_hasher': '2.0.3',
  'hashbrown': '0.14.5',
  'heck': '0.5.0',
  'hermit-abi': '0.3.9',
  'hex': '0.4.3',
  'hmac': '0.12.1',
  'home': '0.5.9',
  'http': '1.1.0',
  'http-body': '1.0.0',
  'http-body-util': '0.1.2',
  'httparse': '1.8.0',
  'httpdate': '1.0.3',
  'humantime': '2.1.0',
  'hyper': '1.3.1',
  'hyper-rustls': '0.27.2',
  'hyper-util': '0.1.5',
  'iana-time-zone': '0.1.60',
  'iana-time-zone-haiku': '0.1.2',
  'idna': '0.5.0',
  'indexmap': '2.2.6',
  'indoc': '2.0.5',
  'inventory': '0.3.15',
  'ipnet': '2.9.0',
  'is-terminal': '0.4.12',
  'itertools': '0.12.1',
  'itoa': '1.0.11',
  'itoap': '1.0.1',
  'jemalloc-sys': '0.5.4+5.3.0-patched',
  'jemallocator': '0.5.4',
  'jobserver': '0.1.31',
  'js-sys': '0.3.69',
  'jsonpath_lib_polars_vendor': '0.0.1',
  'lazy_static': '1.5.0',
  'lexical-core': '0.8.5',
  'lexical-parse-float': '0.8.5',
  'lexical-parse-integer': '0.8.6',
  'lexical-util': '0.8.5',
  'lexical-write-float': '0.8.5',
  'lexical-write-integer': '0.8.5',
  'libc': '0.2.155',
  'libflate': '2.1.0',
  'libflate_lz77': '2.1.0',
  'libgit2-sys': '0.16.2+1.7.2',
  'libloading': '0.8.4',
  'libm': '0.2.8',
  'libmimalloc-sys': '0.1.39',
  'libz-ng-sys': '1.1.15',
  'libz-sys': '1.1.18',
  'linux-raw-sys': '0.4.14',
  'lock_api': '0.4.12',
  'log': '0.4.22',
  'lru': '0.12.3',
  'lz4': '1.25.0',
  'lz4-sys': '1.9.5',
  'lz4_flex': '0.11.3',
  'matrixmultiply': '0.3.8',
  'md-5': '0.10.6',
  'memchr': '2.7.4',
  'memmap2': '0.7.1',
  'memoffset': '0.9.1',
  'mimalloc': '0.1.43',
  'mime': '0.3.17',
  'miniz_oxide': '0.7.4',
  'mio': '0.8.11',
  'multiversion': '0.7.4',
  'multiversion-macros': '0.7.4',
  'ndarray': '0.15.6',
  'now': '0.1.3',
  'ntapi': '0.4.1',
  'num': '0.4.3',
  'num-bigint': '0.4.6',
  'num-complex': '0.4.6',
  'num-conv': '0.1.0',
  'num-integer': '0.1.46',
  'num-iter': '0.1.45',
  'num-rational': '0.4.2',
  'num-traits': '0.2.19',
  'num_cpus': '1.16.0',
  'numpy': '0.21.0',
  'objc-sys': '0.3.5',
  'objc2': '0.5.2',
  'objc2-app-kit': '0.2.2',
  'objc2-core-data': '0.2.2',
  'objc2-core-image': '0.2.2',
  'objc2-encode': '4.0.3',
  'objc2-foundation': '0.2.2',
  'objc2-metal': '0.2.2',
  'objc2-quartz-core': '0.2.2',
  'object': '0.36.1',
  'object_store': '0.10.1',
  'once_cell': '1.19.0',
  'oorandom': '11.1.3',
  'openssl-probe': '0.1.5',
  'outref': '0.5.1',
  'p256': '0.11.1',
  'parking_lot': '0.12.3',
  'parking_lot_core': '0.9.10',
  'parquet-format-safe': '0.2.4',
  'parse-zoneinfo': '0.3.1',
  'percent-encoding': '2.3.1',
  'phf': '0.11.2',
  'phf_codegen': '0.11.2',
  'phf_generator': '0.11.2',
  'phf_shared': '0.11.2',
  'pin-project': '1.1.5',
  'pin-project-internal': '1.1.5',
  'pin-project-lite': '0.2.14',
  'pin-utils': '0.1.0',
  'pkcs8': '0.9.0',
  'pkg-config': '0.3.30',
  'planus': '0.3.1',
  'plotters': '0.3.6',
  'plotters-backend': '0.3.6',
  'plotters-svg': '0.3.6',
  'polars': '0.41.3',
  'polars-arrow': '0.41.3',
  'polars-arrow-format': '0.1.0',
  'polars-compute': '0.41.3',
  'polars-core': '0.41.3',
  'polars-doc-examples': '0.41.3',
  'polars-error': '0.41.3',
  'polars-expr': '0.41.3',
  'polars-ffi': '0.41.3',
  'polars-io': '0.41.3',
  'polars-json': '0.41.3',
  'polars-lazy': '0.41.3',
  'polars-mem-engine': '0.41.3',
  'polars-ops': '0.41.3',
  'polars-parquet': '0.41.3',
  'polars-pipe': '0.41.3',
  'polars-plan': '0.41.3',
  'polars-row': '0.41.3',
  'polars-sql': '0.41.3',
  'polars-stream': '0.41.3',
  'polars-time': '0.41.3',
  'polars-utils': '0.41.3',
  'portable-atomic': '1.6.0',
  'powerfmt': '0.2.0',
  'ppv-lite86': '0.2.17',
  'proc-macro2': '1.0.86',
  'proptest': '1.5.0',
  'prost': '0.11.9',
  'prost-derive': '0.11.9',
  'psm': '0.1.21',
  'py-polars': '1.1.0',
  'pyo3': '0.21.2',
  'pyo3-build-config': '0.21.2',
  'pyo3-ffi': '0.21.2',
  'pyo3-macros': '0.21.2',
  'pyo3-macros-backend': '0.21.2',
  'quad-rand': '0.2.1',
  'quick-xml': '0.31.0',
  'quickcheck': '1.0.3',
  'quinn': '0.11.2',
  'quinn-proto': '0.11.3',
  'quinn-udp': '0.5.2',
  'quote': '1.0.36',
  'rand': '0.8.5',
  'rand_chacha': '0.3.1',
  'rand_core': '0.6.4',
  'rand_distr': '0.4.3',
  'rand_regex': '0.15.1',
  'rand_xorshift': '0.3.0',
  'raw-cpuid': '11.0.2',
  'rawpointer': '0.2.1',
  'rayon': '1.10.0',
  'rayon-core': '1.12.1',
  'recursive': '0.1.1',
  'recursive-proc-macro-impl': '0.1.1',
  'redox_syscall': '0.5.2',
  'ref-cast': '1.0.23',
  'ref-cast-impl': '1.0.23',
  'regex': '1.10.5',
  'regex-automata': '0.4.7',
  'regex-lite': '0.1.6',
  'regex-syntax': '0.8.4',
  'reqwest': '0.12.5',
  'rfc6979': '0.3.1',
  'ring': '0.17.8',
  'rle-decode-fast': '1.0.3',
  'rustc-demangle': '0.1.24',
  'rustc-hash': '1.1.0',
  'rustc_version': '0.4.0',
  'rustix': '0.38.34',
  'rustls': '0.23.10',
  'rustls-native-certs': '0.7.0',
  'rustls-pemfile': '2.1.2',
  'rustls-pki-types': '1.7.0',
  'rustls-webpki': '0.102.4',
  'rustversion': '1.0.17',
  'ryu': '1.0.18',
  'same-file': '1.0.6',
  'sample-arrow2': '0.17.2',
  'sample-std': '0.2.1',
  'sample-test': '0.2.1',
  'sample-test-macros': '0.2.1',
  'schannel': '0.1.23',
  'scopeguard': '1.2.0',
  'sct': '0.7.1',
  'sec1': '0.3.0',
  'security-framework': '2.11.0',
  'security-framework-sys': '2.11.0',
  'semver': '1.0.23',
  'serde': '1.0.203',
  'serde_derive': '1.0.203',
  'serde_json': '1.0.118',
  'serde_spanned': '0.6.6',
  'serde_urlencoded': '0.7.1',
  'sha1': '0.10.6',
  'sha2': '0.10.8',
  'signal-hook-registry': '1.4.2',
  'signature': '1.6.4',
  'simd-json': '0.13.10',
  'simdutf8': '0.1.4',
  'siphasher': '0.3.11',
  'slab': '0.4.9',
  'slotmap': '1.0.7',
  'smallvec': '1.13.2',
  'smartstring': '1.0.1',
  'snafu': '0.7.5',
  'snafu-derive': '0.7.5',
  'snap': '1.1.1',
  'socket2': '0.5.7',
  'spin': '0.9.8',
  'spki': '0.6.0',
  'sqlparser': '0.47.0',
  'stacker': '0.1.15',
  'static_assertions': '1.1.0',
  'streaming-decompression': '0.1.2',
  'streaming-iterator': '0.1.9',
  'strength_reduce': '0.2.4',
  'strum': '0.26.3',
  'strum_macros': '0.26.4',
  'subtle': '2.6.1',
  'syn': '2.0.68',
  'sync_wrapper': '1.0.1',
  'sysinfo': '0.30.12',
  'target-features': '0.1.6',
  'target-lexicon': '0.12.14',
  'tempfile': '3.10.1',
  'thiserror': '1.0.61',
  'thiserror-impl': '1.0.61',
  'time': '0.3.36',
  'time-core': '0.1.2',
  'time-macros': '0.2.18',
  'tiny-keccak': '2.0.2',
  'tinytemplate': '1.2.1',
  'tinyvec': '1.6.1',
  'tinyvec_macros': '0.1.1',
  'tokio': '1.38.0',
  'tokio-macros': '2.3.0',
  'tokio-rustls': '0.26.0',
  'tokio-util': '0.7.11',
  'toml': '0.7.8',
  'toml_datetime': '0.6.6',
  'toml_edit': '0.19.15',
  'tower': '0.4.13',
  'tower-layer': '0.3.2',
  'tower-service': '0.3.2',
  'tracing': '0.1.40',
  'tracing-attributes': '0.1.27',
  'tracing-core': '0.1.32',
  'try-lock': '0.2.5',
  'twox-hash': '1.6.3',
  'typed-builder': '0.16.2',
  'typed-builder-macro': '0.16.2',
  'typenum': '1.17.0',
  'unarray': '0.1.4',
  'unicode-bidi': '0.3.15',
  'unicode-ident': '1.0.12',
  'unicode-normalization': '0.1.23',
  'unicode-reverse': '1.0.9',
  'unicode-segmentation': '1.11.0',
  'unicode-width': '0.1.13',
  'unindent': '0.2.3',
  'untrusted': '0.9.0',
  'url': '2.5.2',
  'urlencoding': '2.1.3',
  'uuid': '1.9.1',
  'value-trait': '0.8.1',
  'vcpkg': '0.2.15',
  'version_check': '0.9.4',
  'vsimd': '0.8.0',
  'walkdir': '2.5.0',
  'want': '0.3.1',
  'wasi': '0.11.0+wasi-snapshot-preview1',
  'wasm-bindgen': '0.2.92',
  'wasm-bindgen-backend': '0.2.92',
  'wasm-bindgen-futures': '0.4.42',
  'wasm-bindgen-macro': '0.2.92',
  'wasm-bindgen-macro-support': '0.2.92',
  'wasm-bindgen-shared': '0.2.92',
  'wasm-streams': '0.4.0',
  'web-sys': '0.3.69',
  'winapi': '0.3.9',
  'winapi-i686-pc-windows-gnu': '0.4.0',
  'winapi-util': '0.1.8',
  'winapi-x86_64-pc-windows-gnu': '0.4.0',
  'windows': '0.52.0',
  'windows-core': '0.52.0',
  'windows-sys': '0.52.0',
  'windows-targets': '0.52.5',
  'windows_aarch64_gnullvm': '0.52.5',
  'windows_aarch64_msvc': '0.52.5',
  'windows_i686_gnu': '0.52.5',
  'windows_i686_gnullvm': '0.52.5',
  'windows_i686_msvc': '0.52.5',
  'windows_x86_64_gnu': '0.52.5',
  'windows_x86_64_gnullvm': '0.52.5',
  'windows_x86_64_msvc': '0.52.5',
  'winnow': '0.5.40',
  'winreg': '0.52.0',
  'x11rb': '0.13.1',
  'x11rb-protocol': '0.13.1',
  'xmlparser': '0.13.6',
  'xxhash-rust': '0.8.10',
  'zerocopy': '0.7.34',
  'zerocopy-derive': '0.7.34',
  'zeroize': '1.8.1',
  'zstd': '0.13.1',
  'zstd-safe': '7.1.0',
  'zstd-sys': '2.0.11+zstd.1.5.6'},
 'features': ['ALL',
  'ARBOARD',
  'ARRAY_ANY_ALL',
  'ARRAY_COUNT',
  'ASOF_JOIN',
  'AVRO',
  'BINARY_ENCODING',
  'BUILD_INFO',
  'CLIPBOARD',
  'CLOUD',
  'CROSS_JOIN',
  'CSE',
  'CSV',
  'CUTQCUT',
  'DECOMPRESS',
  'DEFAULT',
  'DTYPES',
  'DTYPE_ARRAY',
  'DTYPE_I16',
  'DTYPE_I8',
  'DTYPE_U16',
  'DTYPE_U8',
  'EXTRACT_GROUPS',
  'EXTRACT_JSONPATH',
  'FFI_PLUGIN',
  'FIND_MANY',
  'HIST',
  'IO',
  'IPC',
  'IPC_STREAMING',
  'IS_IN',
  'JSON',
  'LIST_ANY_ALL',
  'LIST_COUNT',
  'LIST_DROP_NULLS',
  'LIST_GATHER',
  'LIST_SAMPLE',
  'LIST_SETS',
  'MERGE_SORTED',
  'META',
  'NIGHTLY',
  'OBJECT',
  'OPERATIONS',
  'OPTIMIZATIONS',
  'PARQUET',
  'PCT_CHANGE',
  'PEAKS',
  'PERFORMANT',
  'PIVOT',
  'POLARS_PARQUET',
  'PROPAGATE_NANS',
  'REGEX',
  'REPEAT_BY',
  'RLE',
  'SEARCH_SORTED',
  'SERDE_JSON',
  'SIGN',
  'SQL',
  'STREAMING',
  'TIMEZONES',
  'TOP_K',
  'TRIGONOMETRY'],
 'host': {'triple': 'x86_64-unknown-linux-gnu'},
 'target': {'arch': 'x86_64',
  'os': 'linux',
  'family': 'unix',
  'env': 'gnu',
  'triple': 'x86_64-unknown-linux-gnu',
  'endianness': 'little',
  'pointer-width': '64',
  'profile': 'release'},
 'git': {'version': None, 'dirty': None, 'hash': None, 'head': None},
 'version': '1.1.0'}

In [3]:
pl.show_versions()

--------Version info---------
Polars:               1.1.0
Index type:           UInt32
Platform:             Linux-5.15.0-113-generic-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
--------Version info---------
Polars:               1.1.0
Index type:           UInt32
Platform:             Linux-5.15.0-113-generic-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

In [4]:
flights = pl.read_csv('./data/flights.csv')

In [5]:
flights.head()

shape: (5, 110)
┌──────┬─────────┬───────┬────────────┬───┬──────────────────┬───────────────┬─────────────┬──────┐
│ Year ┆ Quarter ┆ Month ┆ DayofMonth ┆ … ┆ Div5LongestGTime ┆ Div5WheelsOff ┆ Div5TailNum ┆      │
│ ---  ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ---              ┆ ---           ┆ ---         ┆ ---  │
│ i64  ┆ i64     ┆ i64   ┆ i64        ┆   ┆ str              ┆ str           ┆ str         ┆ str  │
╞══════╪═════════╪═══════╪════════════╪═══╪══════════════════╪═══════════════╪═════════════╪══════╡
│ 2022 ┆ 1       ┆ 1     ┆ 14         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 15         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 16         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 17         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 18         ┆ … ┆ null             ┆               ┆             ┆ null │
└──────┴─────────┴───────┴────────────┴───┴──────────────────┴───────────────┴─────────────┴──────┘

In [6]:
flights.shape

(999, 110)

In [8]:
type(flights[:, 'Month'])

polars.series.series.Series

In [9]:
flights.dtypes

[Int64,
 Int64,
 Int64,
 Int64,
 Int64,
 String,
 String,
 Int64,
 String,
 String,
 Int64,
 Int64,
 Int64,
 Int64,
 String,
 String,
 String,
 Int64,
 String,
 Int64,
 Int64,
 Int64,
 Int64,
 String,
 String,
 String,
 Int64,
 String,
 Int64,
 Int64,
 String,
 Float64,
 Float64,
 Float64,
 Int64,
 String,
 Float64,
 String,
 String,
 Float64,
 Int64,
 String,
 Float64,
 Float64,
 Float64,
 Int64,
 String,
 Float64,
 String,
 Float64,
 Float64,
 Float64,
 Float64,
 Float64,
 Float64,
 Int64,
 Float64,
 Float64,
 Float64,
 Float64,
 Float64,
 String,
 Float64,
 Float64,
 Int64,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String]

In [10]:
full_flights = pl.read_csv('./data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_1.csv')

In [11]:
full_flights.shape

(537902, 110)

In [13]:
full_flights.estimated_size('mb')

240.02855968475342

In [14]:
full_flights.describe()

shape: (9, 111)
┌────────────┬──────────┬──────────┬──────────┬───┬──────────────────┬───────────────┬─────────────┬────────┐
│ statistic  ┆ Year     ┆ Quarter  ┆ Month    ┆ … ┆ Div5LongestGTime ┆ Div5WheelsOff ┆ Div5TailNum ┆        │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---              ┆ ---           ┆ ---         ┆ ---    │
│ str        ┆ f64      ┆ f64      ┆ f64      ┆   ┆ str              ┆ str           ┆ str         ┆ str    │
╞════════════╪══════════╪══════════╪══════════╪═══╪══════════════════╪═══════════════╪═════════════╪════════╡
│ count      ┆ 537902.0 ┆ 537902.0 ┆ 537902.0 ┆ … ┆ 0                ┆ 537902        ┆ 537902      ┆ 0      │
│ null_count ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ … ┆ 537902           ┆ 0             ┆ 0           ┆ 537902 │
│ mean       ┆ 2022.0   ┆ 1.0      ┆ 1.0      ┆ … ┆ null             ┆ null          ┆ null        ┆ null   │
│ std        ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ … ┆ null             ┆ null          ┆ null        ┆ null   │
│ min        ┆ 2022.0   ┆ 1.0      ┆ 1.0      ┆ … ┆ null             ┆               ┆             ┆ null   │
│ 25%        ┆ 2022.0   ┆ 1.0      ┆ 1.0      ┆ … ┆ null             ┆ null          ┆ null        ┆ null   │
│ 50%        ┆ 2022.0   ┆ 1.0      ┆ 1.0      ┆ … ┆ null             ┆ null          ┆ null        ┆ null   │
│ 75%        ┆ 2022.0   ┆ 1.0      ┆ 1.0      ┆ … ┆ null             ┆ null          ┆ null        ┆ null   │
│ max        ┆ 2022.0   ┆ 1.0      ┆ 1.0      ┆ … ┆ null             ┆               ┆             ┆ null   │
└────────────┴──────────┴──────────┴──────────┴───┴──────────────────┴───────────────┴─────────────┴────────┘

In [15]:
full_flights['Year'].value_counts()

shape: (1, 2)
┌──────┬────────┐
│ Year ┆ count  │
│ ---  ┆ ---    │
│ i64  ┆ u32    │
╞══════╪════════╡
│ 2022 ┆ 537902 │
└──────┴────────┘

In [17]:
full_flights['Quarter'].value_counts()

shape: (1, 2)
┌─────────┬────────┐
│ Quarter ┆ count  │
│ ---     ┆ ---    │
│ i64     ┆ u32    │
╞═════════╪════════╡
│ 1       ┆ 537902 │
└─────────┴────────┘

In [18]:
full_flights['Month'].value_counts()

shape: (1, 2)
┌───────┬────────┐
│ Month ┆ count  │
│ ---   ┆ ---    │
│ i64   ┆ u32    │
╞═══════╪════════╡
│ 1     ┆ 537902 │
└───────┴────────┘

In [19]:
full_flights['DayofMonth'].value_counts().sort('DayofMonth').head(10)

shape: (10, 2)
┌────────────┬───────┐
│ DayofMonth ┆ count │
│ ---        ┆ ---   │
│ i64        ┆ u32   │
╞════════════╪═══════╡
│ 1          ┆ 15852 │
│ 2          ┆ 19058 │
│ 3          ┆ 19216 │
│ 4          ┆ 16965 │
│ 5          ┆ 16863 │
│ 6          ┆ 18235 │
│ 7          ┆ 18241 │
│ 8          ┆ 15303 │
│ 9          ┆ 18157 │
│ 10         ┆ 17897 │
└────────────┴───────┘

In [20]:
full_flights.filter(pl.col('OriginStateName') == 'Ohio')

shape: (7_434, 110)
┌──────┬─────────┬───────┬────────────┬───┬──────────────────┬───────────────┬─────────────┬──────┐
│ Year ┆ Quarter ┆ Month ┆ DayofMonth ┆ … ┆ Div5LongestGTime ┆ Div5WheelsOff ┆ Div5TailNum ┆      │
│ ---  ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ---              ┆ ---           ┆ ---         ┆ ---  │
│ i64  ┆ i64     ┆ i64   ┆ i64        ┆   ┆ str              ┆ str           ┆ str         ┆ str  │
╞══════╪═════════╪═══════╪════════════╪═══╪══════════════════╪═══════════════╪═════════════╪══════╡
│ 2022 ┆ 1       ┆ 1     ┆ 14         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 15         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 16         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 17         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 18         ┆ … ┆ null             ┆               ┆             ┆ null │
│ …    ┆ …       ┆ …     ┆ …          ┆ … ┆ …                ┆ …             ┆ …           ┆ …    │
│ 2022 ┆ 1       ┆ 1     ┆ 6          ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 6          ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 6          ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 6          ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 6          ┆ … ┆ null             ┆               ┆             ┆ null │
└──────┴─────────┴───────┴────────────┴───┴──────────────────┴───────────────┴─────────────┴──────┘

In [21]:
full_flights.filter(pl.col('DestStateName') == 'Virginia').head()

shape: (5, 110)
┌──────┬─────────┬───────┬────────────┬───┬──────────────────┬───────────────┬─────────────┬──────┐
│ Year ┆ Quarter ┆ Month ┆ DayofMonth ┆ … ┆ Div5LongestGTime ┆ Div5WheelsOff ┆ Div5TailNum ┆      │
│ ---  ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ---              ┆ ---           ┆ ---         ┆ ---  │
│ i64  ┆ i64     ┆ i64   ┆ i64        ┆   ┆ str              ┆ str           ┆ str         ┆ str  │
╞══════╪═════════╪═══════╪════════════╪═══╪══════════════════╪═══════════════╪═════════════╪══════╡
│ 2022 ┆ 1       ┆ 1     ┆ 14         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 15         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 16         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 17         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 18         ┆ … ┆ null             ┆               ┆             ┆ null │
└──────┴─────────┴───────┴────────────┴───┴──────────────────┴───────────────┴─────────────┴──────┘

In [22]:
full_flights.filter(
    pl.col('OriginStateName') == 'Ohio', 
    ~(pl.col('DestStateName') == 'Virginia')
).shape

(6870, 110)

### Select

In [23]:
foo = pl.Series('foo', [1, 2, 3])
bar = pl.Series('bar', [4, 5, 6])

pl.select(mmin = pl.min_horizontal(foo, bar))

shape: (3, 1)
┌──────┐
│ mmin │
│ ---  │
│ i64  │
╞══════╡
│ 1    │
│ 2    │
│ 3    │
└──────┘

In [24]:
pl.select(foo, bar)

shape: (3, 2)
┌─────┬─────┐
│ foo ┆ bar │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 4   │
│ 2   ┆ 5   │
│ 3   ┆ 6   │
└─────┴─────┘

In [25]:
full_flights.select(['FlightDate', 'Tail_Number']).head(3)

shape: (3, 2)
┌────────────┬─────────────┐
│ FlightDate ┆ Tail_Number │
│ ---        ┆ ---         │
│ str        ┆ str         │
╞════════════╪═════════════╡
│ 2022-01-14 ┆ N119HQ      │
│ 2022-01-15 ┆ N122HQ      │
│ 2022-01-16 ┆ N412YX      │
└────────────┴─────────────┘

In [26]:
full_flights.select(pl.col(['FlightDate', 'Tail_Number'])).head(3)

shape: (3, 2)
┌────────────┬─────────────┐
│ FlightDate ┆ Tail_Number │
│ ---        ┆ ---         │
│ str        ┆ str         │
╞════════════╪═════════════╡
│ 2022-01-14 ┆ N119HQ      │
│ 2022-01-15 ┆ N122HQ      │
│ 2022-01-16 ┆ N412YX      │
└────────────┴─────────────┘

In [27]:
full_flights.select(pl.col(pl.Int64)).columns

['Year',
 'Quarter',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'DOT_ID_Reporting_Airline',
 'Flight_Number_Reporting_Airline',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'OriginStateFips',
 'OriginWac',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'DestStateFips',
 'DestWac',
 'CRSDepTime',
 'DepartureDelayGroups',
 'CRSArrTime',
 'ArrivalDelayGroups',
 'DistanceGroup',
 'DivAirportLandings']

In [23]:
full_flights.select(
    pl.col(pl.Int64),
    pl.col(pl.Float64)
).columns

['Year',
 'Quarter',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'DOT_ID_Reporting_Airline',
 'Flight_Number_Reporting_Airline',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'OriginStateFips',
 'OriginWac',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'DestStateFips',
 'DestWac',
 'CRSDepTime',
 'DepartureDelayGroups',
 'CRSArrTime',
 'ArrivalDelayGroups',
 'DistanceGroup',
 'DivAirportLandings',
 'DepDelay',
 'DepDelayMinutes',
 'DepDel15',
 'TaxiOut',
 'TaxiIn',
 'ArrDelay',
 'ArrDelayMinutes',
 'ArrDel15',
 'Cancelled',
 'Diverted',
 'CRSElapsedTime',
 'ActualElapsedTime',
 'AirTime',
 'Flights',
 'Distance',
 'CarrierDelay',
 'WeatherDelay',
 'NASDelay',
 'SecurityDelay',
 'LateAircraftDelay',
 'TotalAddGTime',
 'LongestAddGTime']

In [24]:
import polars.selectors as cs

In [25]:
full_flights.select(cs.all()).head(3)

shape: (3, 110)
┌──────┬─────────┬───────┬────────────┬───┬──────────────────┬───────────────┬─────────────┬──────┐
│ Year ┆ Quarter ┆ Month ┆ DayofMonth ┆ … ┆ Div5LongestGTime ┆ Div5WheelsOff ┆ Div5TailNum ┆      │
│ ---  ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ---              ┆ ---           ┆ ---         ┆ ---  │
│ i64  ┆ i64     ┆ i64   ┆ i64        ┆   ┆ str              ┆ str           ┆ str         ┆ str  │
╞══════╪═════════╪═══════╪════════════╪═══╪══════════════════╪═══════════════╪═════════════╪══════╡
│ 2022 ┆ 1       ┆ 1     ┆ 14         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 15         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 16         ┆ … ┆ null             ┆               ┆             ┆ null │
└──────┴─────────┴───────┴────────────┴───┴──────────────────┴───────────────┴─────────────┴──────┘

In [26]:
full_flights.select(
    cs.starts_with('Flight') | cs.ends_with('Delay')
).head(3)

shape: (3, 11)
┌────────────┬────────────┬─────────┬──────────┬───┬──────────┬────────────┬───────────┬───────────┐
│ FlightDate ┆ Flight_Num ┆ Flights ┆ DepDelay ┆ … ┆ NASDelay ┆ SecurityDe ┆ LateAircr ┆ DivArrDel │
│ ---        ┆ ber_Report ┆ ---     ┆ ---      ┆   ┆ ---      ┆ lay        ┆ aftDelay  ┆ ay        │
│ str        ┆ ing_Airlin ┆ f64     ┆ f64      ┆   ┆ f64      ┆ ---        ┆ ---       ┆ ---       │
│            ┆ e          ┆         ┆          ┆   ┆          ┆ f64        ┆ f64       ┆ str       │
│            ┆ ---        ┆         ┆          ┆   ┆          ┆            ┆           ┆           │
│            ┆ i64        ┆         ┆          ┆   ┆          ┆            ┆           ┆           │
╞════════════╪════════════╪═════════╪══════════╪═══╪══════════╪════════════╪═══════════╪═══════════╡
│ 2022-01-14 ┆ 4879       ┆ 1.0     ┆ -3.0     ┆ … ┆ null     ┆ null       ┆ null      ┆ null      │
│ 2022-01-15 ┆ 4879       ┆ 1.0     ┆ -10.0    ┆ … ┆ null     ┆ null       ┆ null      ┆ null      │
│ 2022-01-16 ┆ 4879       ┆ 1.0     ┆ -6.0     ┆ … ┆ null     ┆ null       ┆ null      ┆ null      │
└────────────┴────────────┴─────────┴──────────┴───┴──────────┴────────────┴───────────┴───────────┘

In [27]:
full_flights.select(
    cs.by_dtype(pl.INTEGER_DTYPES)
).columns

['Year',
 'Quarter',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'DOT_ID_Reporting_Airline',
 'Flight_Number_Reporting_Airline',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'OriginStateFips',
 'OriginWac',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'DestStateFips',
 'DestWac',
 'CRSDepTime',
 'DepartureDelayGroups',
 'CRSArrTime',
 'ArrivalDelayGroups',
 'DistanceGroup',
 'DivAirportLandings']

In [28]:
flights.columns[flights.columns == 'Year':flights.columns == 'Tail_Number']

[]

In [29]:
flights.get_column_index('Year'); flights.get_column_index('Tail_Number')

9

In [30]:
flights[:,0:9].head(3)

shape: (3, 9)
┌──────┬─────────┬───────┬────────────┬───┬────────────┬──────────────┬──────────────┬─────────────┐
│ Year ┆ Quarter ┆ Month ┆ DayofMonth ┆ … ┆ FlightDate ┆ Reporting_Ai ┆ DOT_ID_Repor ┆ IATA_CODE_R │
│ ---  ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ---        ┆ rline        ┆ ting_Airline ┆ eporting_Ai │
│ i64  ┆ i64     ┆ i64   ┆ i64        ┆   ┆ str        ┆ ---          ┆ ---          ┆ rline       │
│      ┆         ┆       ┆            ┆   ┆            ┆ str          ┆ i64          ┆ ---         │
│      ┆         ┆       ┆            ┆   ┆            ┆              ┆              ┆ str         │
╞══════╪═════════╪═══════╪════════════╪═══╪════════════╪══════════════╪══════════════╪═════════════╡
│ 2022 ┆ 1       ┆ 1     ┆ 14         ┆ … ┆ 2022-01-14 ┆ YX           ┆ 20452        ┆ YX          │
│ 2022 ┆ 1       ┆ 1     ┆ 15         ┆ … ┆ 2022-01-15 ┆ YX           ┆ 20452        ┆ YX          │
│ 2022 ┆ 1       ┆ 1     ┆ 16         ┆ … ┆ 2022-01-16 ┆ YX           ┆ 20452        ┆ YX          │
└──────┴─────────┴───────┴────────────┴───┴────────────┴──────────────┴──────────────┴─────────────┘

In [31]:
flights[:,flights.get_column_index('Year'):flights.get_column_index('Tail_Number')].head(3)

shape: (3, 9)
┌──────┬─────────┬───────┬────────────┬───┬────────────┬──────────────┬──────────────┬─────────────┐
│ Year ┆ Quarter ┆ Month ┆ DayofMonth ┆ … ┆ FlightDate ┆ Reporting_Ai ┆ DOT_ID_Repor ┆ IATA_CODE_R │
│ ---  ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ---        ┆ rline        ┆ ting_Airline ┆ eporting_Ai │
│ i64  ┆ i64     ┆ i64   ┆ i64        ┆   ┆ str        ┆ ---          ┆ ---          ┆ rline       │
│      ┆         ┆       ┆            ┆   ┆            ┆ str          ┆ i64          ┆ ---         │
│      ┆         ┆       ┆            ┆   ┆            ┆              ┆              ┆ str         │
╞══════╪═════════╪═══════╪════════════╪═══╪════════════╪══════════════╪══════════════╪═════════════╡
│ 2022 ┆ 1       ┆ 1     ┆ 14         ┆ … ┆ 2022-01-14 ┆ YX           ┆ 20452        ┆ YX          │
│ 2022 ┆ 1       ┆ 1     ┆ 15         ┆ … ┆ 2022-01-15 ┆ YX           ┆ 20452        ┆ YX          │
│ 2022 ┆ 1       ┆ 1     ┆ 16         ┆ … ┆ 2022-01-16 ┆ YX           ┆ 20452        ┆ YX          │
└──────┴─────────┴───────┴────────────┴───┴────────────┴──────────────┴──────────────┴─────────────┘

In [32]:
flights.select(
    cs.matches('Div2')
).columns

['Div2Airport',
 'Div2AirportID',
 'Div2AirportSeqID',
 'Div2WheelsOn',
 'Div2TotalGTime',
 'Div2LongestGTime',
 'Div2WheelsOff',
 'Div2TailNum']

In [33]:
print(range(3, 13))

range(3, 13)

In [34]:
for i in range(3, 4):
    print(i)

3

In [35]:
%%time
full_flights.select(
    cs.matches('Div2')
).columns

CPU times: user 838 µs, sys: 0 ns, total: 838 µs
Wall time: 1.07 ms

['Div2Airport',
 'Div2AirportID',
 'Div2AirportSeqID',
 'Div2WheelsOn',
 'Div2TotalGTime',
 'Div2LongestGTime',
 'Div2WheelsOff',
 'Div2TailNum']

In [36]:
%%time
count_flights = (
    pl.scan_csv('./data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_*.csv')
    .filter(
        pl.col('OriginStateName') == 'Ohio'
    )
    .group_by(['Year', 'Month'])
    .agg(
        pl.len().alias('number of flights from Ohio')
    )
    .collect()
)

CPU times: user 5.67 s, sys: 268 ms, total: 5.94 s
Wall time: 883 ms

PARTITIONED DS

In [37]:
count_flights.sort(['Year', 'Month'])

shape: (12, 3)
┌──────┬───────┬─────────────────────────────┐
│ Year ┆ Month ┆ number of flights from Ohio │
│ ---  ┆ ---   ┆ ---                         │
│ i64  ┆ i64   ┆ u32                         │
╞══════╪═══════╪═════════════════════════════╡
│ 2022 ┆ 1     ┆ 7434                        │
│ 2022 ┆ 2     ┆ 6916                        │
│ 2022 ┆ 3     ┆ 7887                        │
│ 2022 ┆ 4     ┆ 7610                        │
│ 2022 ┆ 5     ┆ 7663                        │
│ …    ┆ …     ┆ …                           │
│ 2022 ┆ 8     ┆ 7379                        │
│ 2022 ┆ 9     ┆ 7230                        │
│ 2022 ┆ 10    ┆ 7529                        │
│ 2022 ┆ 11    ┆ 7164                        │
│ 2022 ┆ 12    ┆ 7188                        │
└──────┴───────┴─────────────────────────────┘

In [45]:
%%time
(
    pl.scan_csv('./data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_*.csv')
    .group_by(['Year', 'Reporting_Airline'])
    .agg(
        pl.len().alias('number of rows')
    )
    .collect()
)

CPU times: user 5.61 s, sys: 577 ms, total: 6.18 s
Wall time: 1 s

PARTITIONED DS

shape: (17, 3)
┌──────┬───────────────────┬────────────────┐
│ Year ┆ Reporting_Airline ┆ number of rows │
│ ---  ┆ ---               ┆ ---            │
│ i64  ┆ str               ┆ u32            │
╞══════╪═══════════════════╪════════════════╡
│ 2022 ┆ AS                ┆ 228384         │
│ 2022 ┆ G4                ┆ 116877         │
│ 2022 ┆ B6                ┆ 273058         │
│ 2022 ┆ NK                ┆ 232400         │
│ 2022 ┆ YX                ┆ 316524         │
│ …    ┆ …                 ┆ …              │
│ 2022 ┆ YV                ┆ 114779         │
│ 2022 ┆ QX                ┆ 88791          │
│ 2022 ┆ DL                ┆ 893172         │
│ 2022 ┆ WN                ┆ 1307149        │
│ 2022 ┆ 9E                ┆ 231941         │
└──────┴───────────────────┴────────────────┘

In [43]:
flights = pl.read_csv(
    source='./data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_12.csv',
    separator=',',                  # single character used to separate fields, default=True
    has_header=True,                # flag the first row has header or not, default=True
    infer_schema_length=1000,       # maximum number of lines to read to infer schema, default=100
    n_rows=10                       # maximum number of lines to read
)

In [41]:
flights.head(3)

shape: (3, 110)
┌──────┬─────────┬───────┬────────────┬───┬──────────────────┬───────────────┬─────────────┬──────┐
│ Year ┆ Quarter ┆ Month ┆ DayofMonth ┆ … ┆ Div5LongestGTime ┆ Div5WheelsOff ┆ Div5TailNum ┆      │
│ ---  ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ---              ┆ ---           ┆ ---         ┆ ---  │
│ i64  ┆ i64     ┆ i64   ┆ i64        ┆   ┆ str              ┆ str           ┆ str         ┆ str  │
╞══════╪═════════╪═══════╪════════════╪═══╪══════════════════╪═══════════════╪═════════════╪══════╡
│ 2022 ┆ 4       ┆ 12    ┆ 19         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 4       ┆ 12    ┆ 20         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 4       ┆ 12    ┆ 21         ┆ … ┆ null             ┆               ┆             ┆ null │
└──────┴─────────┴───────┴────────────┴───┴──────────────────┴───────────────┴─────────────┴──────┘